name: Create PR from dev to main

on:
  push:
    branches:
      - dev

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check for existing PR
        id: check-pr
        run: |
          if gh pr list --base main --head dev --json number | jq -e '.[] | select(.number)' > /dev/null; then
            echo "pr_exists=true" >> $GITHUB_ENV
            exit 0
          else
            echo "pr_exists=false" >> $GITHUB_ENV
          fi
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: create pull request
        if: env.pr_exists == 'false'
        run: |
          gh pr create -B main -H dev --title 'Merge dev to main' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}