name: Create PR from dev to main

on:
  push:
    branches:
      - dev

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check for existing PR
        id: check-for-existing-pr
        run: |
          PR_LIST_RESP=$(gh pr list --base main --head dev --json number)
          PR_NUMBER=$(echo "$PR_LIST_RESP" | jq -r '.[0].number')

          if [[ "$PR_NUMBER" =~ ^[0-9]+$ ]]; then
            echo "pr_exists=true" >> $GITHUB_ENV
            echo "pr_number=$PR_NUMBER" >> $GITHUB_ENV
            echo "Existing PR found: '$PR_NUMBER'"
          else
            echo "pr_exists=false" >> $GITHUB_ENV
            echo "No existing PR, Creating new PR..."
          fi
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create new PR
        id: create-pr
        if: env.pr_exists == 'false'
        run: |
          CREATE_PR_RESP=$(gh pr create --base main --head dev --title "Merge dev into main" --body "Auto-generated PR to merge changes from dev to main.")
          PR_NUMBER=$(echo "$CREATE_PR_RESP" | grep -oP '\d+$')
          
          echo "pr_number=$PR_NUMBER" >> $GITHUB_ENV
          echo "New PR: '$PR_NUMBER'"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Merge Pull Request
        id: merge-pr
        run: |
          if gh pr merge ${{ env.pr_number }} --merge 
          then
            echo "Pull request #${{ env.pr_number }} merged successfully."
          else
            echo "Failed to merge pull request #${{ env.pr_number }}."
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}