name: Merging Process

on:
  workflow_call:
    inputs:
      base:
        required: true
        type: string
      compare:
        required: true
        type: string
    secrets:
      gh_token:
        required: true

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.compare }}

      - name: Check for existing PR
        id: check-for-existing-pr
        run: |
          PR_LIST_RESP=$(gh pr list --base ${{ inputs.base }} --head ${{ inputs.compare }} --json number)
          PR_NUMBER=$(echo "$PR_LIST_RESP" | jq -r '.[0].number')

          if [[ "$PR_NUMBER" =~ ^[0-9]+$ ]]; then
            echo "::set-output name=pr_exists::true"
            echo "::set-output name=pr_number::$PR_NUMBER"
            echo "Existing PR found: '$PR_NUMBER'"
          else
            echo "::set-output name=pr_exists::false"
            echo "No existing PR, Creating new PR"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.gh_token }}
    
      - name: Check for new commits
        id: check-for-new-commits
        if: steps.check-for-existing-pr.outputs.pr_exists == 'false'
        run: |
          COMMITS_COUNT=$(git rev-list --count ${{ inputs.compare }}..${{ inputs.base }})
          
          if [ "$COMMITS_COUNT" -eq 0 ]; then
            echo "No new commits found"
            echo "::set-output name=new_commits::false"
          else
            echo "::set-output name=new_commits::true"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.gh_token }}

      - name: Create new PR
        id: create-pr
        if: steps.check-for-existing-pr.outputs.pr_exists == 'false' && steps.check-for-new-commits.outputs.new_commits == 'true'
        run: |
          CREATE_PR_RESP=$(gh pr create --base ${{ inputs.base }} --head ${{ inputs.compare }} --title "Merging ${{ inputs.compare }} into ${{ inputs.base }}" --body "Auto-generated PR to merge changes from ${{ inputs.compare }} to ${{ inputs.base }}.")
          PR_NUMBER=$(echo "$CREATE_PR_RESP" | grep -oP '\d+$')

          echo "::set-output name=pr_number::$PR_NUMBER"
          echo "::set-output name=pr_created::true"
          echo "New PR: '$PR_NUMBER'"
        env:
          GITHUB_TOKEN: ${{ secrets.gh_token }}

      - name: Wait for 1 min
        run: sleep 60

      - name: Check for conflicts
        id: check-for-conflicts
        if: steps.check-for-existing-pr.outputs.pr_exists == 'true' || steps.create-pr.outputs.pr_created == 'true'
        run: |
          PR_NUMBER=${{ steps.create-pr.outputs.pr_number || steps.check-for-existing-pr.outputs.pr_number }}
          PR_MERGEABLE_STATUS=$(gh pr view $PR_NUMBER --json mergeable --jq '.mergeable')

          echo "PR MERGABLE: '$PR_MERGEABLE_STATUS'"

          if [[ "$PR_MERGEABLE_STATUS" == "MERGEABLE" ]]; then
            echo "::set-output name=pr_mergeable::true"
            echo "PR '$PR_NUMBER' is mergeable"
          else
            echo "::set-output name=pr_mergeable::false"
            echo "PR '$PR_NUMBER' has conflicts"
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.gh_token }}

      - name: Merge PR
        id: merge-pr
        if: steps.check-for-conflicts.outputs.pr_mergeable == 'true'
        run: |
          PR_NUMBER=${{ steps.create-pr.outputs.pr_number || steps.check-for-existing-pr.outputs.pr_number }}
          if gh pr merge $PR_NUMBER --merge 
          then
            echo "Pull request $PR_NUMBER merged successfully"
          else
            echo "Failed to merge pull request $PR_NUMBER"
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.gh_token }}
