name: Merging Process

on:
  workflow_call:
    inputs:
      base:
        required: true
        type: string
      compare:
        required: true
        type: string
    secrets:
      gh_token:
        required: true

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.compare }}

      - name: Check for existing PR
        id: check-for-existing-pr
        run: |
          PR_LIST_RESP=$(gh pr list --base ${{ inputs.base }} --head ${{ inputs.compare }} --json number)
          PR_NUMBER=$(echo "$PR_LIST_RESP" | jq -r '.[0].number')

          if [[ "$PR_NUMBER" =~ ^[0-9]+$ ]]; then
            echo "pr_exists=true" >> $GITHUB_ENV
            echo "pr_number=$PR_NUMBER" >> $GITHUB_ENV
            echo "Existing PR found: '$PR_NUMBER'"
          else
            echo "pr_exists=false" >> $GITHUB_ENV
            echo "No existing PR, Creating new PR"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.gh_token }}
    
      - name: Check for new commits
        id: check-for-new-commits
        if: env.pr_exists == 'false'
        run: |
          git fetch --all
          COMMITS_COUNT=$(git rev-list --count origin/${{ inputs.base }}..origin/${{ inputs.compare }})
          
          echo "COMMITS_COUNT: '$COMMITS_COUNT'"

          if [ "$COMMITS_COUNT" -eq 0 ]; then
            echo "No new commits found"
            echo "new_commits=false" >> $GITHUB_ENV
          else
            echo "new_commits=true" >> $GITHUB_ENV
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.gh_token }}

      - name: Create new PR
        id: create-pr
        if: env.pr_exists == 'false' && env.new_commits == 'true'
        run: |
          CREATE_PR_RESP=$(gh pr create --base ${{ inputs.base }} --head ${{ inputs.compare }} --title "Merging ${{ inputs.compare }} into ${{ inputs.base }}" --body "Auto-generated PR to merge changes from ${{ inputs.compare }} to ${{ inputs.base }}.")
          PR_NUMBER=$(echo "$CREATE_PR_RESP" | grep -oP '\d+$')

          echo "pr_number=$PR_NUMBER" >> $GITHUB_ENV
          echo "pr_created=true" >> $GITHUB_ENV
          echo "New PR: '$PR_NUMBER'"
        env:
          GITHUB_TOKEN: ${{ secrets.gh_token }}

      - name: Wait for 1 min
        run: sleep 60

      - name: Check for conflicts
        id: check-for-conflicts
        if: env.pr_exists == 'true' || env.pr_created == 'true'
        run: |
          PR_NUMBER=${{ env.pr_number }}
          PR_MERGEABLE_STATUS=$(gh pr view $PR_NUMBER --json mergeable --jq '.mergeable')

          echo "PR MERGABLE: '$PR_MERGEABLE_STATUS'"

          if [[ "$PR_MERGEABLE_STATUS" == "MERGEABLE" ]]; then
            echo "pr_mergeable=true" >> $GITHUB_ENV
            echo "PR '$PR_NUMBER' is mergeable"
          else
            echo "pr_mergeable=false" >> $GITHUB_ENV
            echo "PR '$PR_NUMBER' has conflicts"
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.gh_token }}

      - name: Merge PR
        id: merge-pr
        run: |
          if [ "${{ env.pr_mergeable }}" == "true" ]; then
            PR_NUMBER=${{ env.pr_number }}
            if gh pr merge $PR_NUMBER --merge 
            then
              echo "Pull request $PR_NUMBER merged successfully"
            else
              echo "Failed to merge pull request $PR_NUMBER"
              exit 1
            fi
          else
            echo "Failed to merge pull request $PR_NUMBER"
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.gh_token }}
