name: AsInt Bot [Sandbox -> AIS-02]

on:
  schedule:
    - cron: "0 5 * * 1-5"
    - cron: "0 8 * * 1-5"
    - cron: "0 11 * * 1-5"
  workflow_dispatch:

jobs:
  merging-process:
    uses: ./.github/workflows/_auto_merge.yml
    with:
      base: "dev-ais-02"
      compare: "sandbox"
    secrets: inherit