name: Schema Deployment

on:
  workflow_call:
    inputs:
      cf_api:
        description: 'Cloud Foundry API endpoint'
        required: true
        type: string
      cf_org:
        description: 'Cloud Foundry Organization'
        required: true
        type: string
      cf_space:
        description: 'Cloud Foundry Space'
        required: true
        type: string
      branch:
        description: 'Branch to checkout before deployment'
        required: true
        type: string
      hdi_name:
        description: 'HDI Instance name'
        required: true
        type: string
    # secrets:
    #   cf_username:
    #     description: 'Cloud Foundry Username'
    #     required: true
    #   cf_password:
    #     description: 'Cloud Foundry PAssword'
    #     required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install CF CLI
      run: |
        wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
        echo "deb http://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
        sudo apt-get update
        sudo apt-get install cf-cli

    - name: Install CDS CLI
      run: npm install -g @sap/cds-dk

    - name: Log in to Cloud Foundry
      run: |
        echo "Secret: $CF_USERNAME"
        cf api ${{ inputs.cf_api }}
        cf auth $CF_USERNAME $secrets.CF_PASSWORD
        cf target -o ${{ inputs.cf_org }} -s ${{ inputs.cf_space }}
      env:
        CF_USERNAME: ${{ secrets._CF_USERNAME }}
        CF_PASSWORD: ${{ secrets._CF_PASSWORD }}
    - name: Deploy CDS Schema
      run: cds deploy --to hana:${{ inputs.hdi_name }}
